"""
db/models.py
============
Pydantic v2 data models for the Naavya / NeoTriage database layer.

PRIVACY NOTICE
--------------
These models are intentionally PII-free.  Do NOT add fields for:
  - Mother's name, husband's name, or ASHA worker's name
  - Phone numbers or device identifiers
  - Village, district, or any geographic address
  - Age, religion, caste, or any demographic attribute

The only identifier stored is `conversation_id`, which is a random UUID
generated per interaction and carries no personal meaning on its own.

Models
------
SessionState       — live triage conversation state (one doc per session).
InteractionLog     — append-only audit record of each pipeline stage.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    """Return the current UTC time as a timezone-aware datetime."""
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# SessionState
# ---------------------------------------------------------------------------

class SessionState(BaseModel):
    """
    Represents the live state of a single triage conversation.

    One document per ``conversation_id``.  Updated (upserted) after each
    pipeline stage so any service can pick up a session mid-flight.

    Attributes
    ----------
    conversation_id:
        Opaque UUID that links all pipeline stages for this interaction.
        Generated by the caller; never derived from personal data.
    status:
        Current lifecycle stage.  One of:
        ``"intake"`` | ``"disambiguating"`` | ``"classified"`` | ``"expired"``
    extracted_signs:
        Dictionary of danger signs confirmed so far, keyed by sign name.
        Example: ``{"fast_breathing": True, "chest_indrawing": False}``
    pending_question:
        The last disambiguation question sent to the mother, if any.
        ``None`` when no follow-up is pending.
    risk_level:
        Classification output from the risk-combination agent.
        One of: ``"reassure"`` | ``"contact_asha"`` | ``"refer_now"`` | ``None``
    created_at:
        UTC timestamp of session creation (set once on first upsert).
    updated_at:
        UTC timestamp of the most recent update.
    """

    conversation_id: str = Field(
        ...,
        description="Opaque UUID; the sole cross-pipeline correlation key.",
    )
    status: str = Field(
        ...,
        description=(
            "One of: 'intake' | 'disambiguating' | 'classified' | 'expired'"
        ),
    )
    extracted_signs: dict[str, Any] = Field(
        default_factory=dict,
        description="Danger-sign key/value pairs confirmed so far.",
    )
    pending_question: Optional[str] = Field(
        default=None,
        description="Last disambiguation question sent to the mother.",
    )
    risk_level: Optional[str] = Field(
        default=None,
        description=(
            "Risk classification: 'reassure' | 'contact_asha' | 'refer_now'"
        ),
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        description="UTC timestamp of first session creation.",
    )
    updated_at: datetime = Field(
        default_factory=_utcnow,
        description="UTC timestamp of most recent update.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "conversation_id": "c8e4f3a1-2b7d-4e9a-a012-0f1c3d5e7b89",
                "status": "classified",
                "extracted_signs": {"fast_breathing": True, "poor_feeding": True},
                "pending_question": None,
                "risk_level": "refer_now",
            }
        }
    }


# ---------------------------------------------------------------------------
# InteractionLog
# ---------------------------------------------------------------------------

class InteractionLog(BaseModel):
    """
    Immutable audit record written after each pipeline stage completes.

    Append-only — documents in ``interaction_logs`` are never modified.

    Attributes
    ----------
    conversation_id:
        Same opaque UUID as the parent ``SessionState``.
    stage:
        Pipeline stage that produced this record.
        One of: ``"asr"`` | ``"intake"`` | ``"disambiguation"``
        | ``"risk_combination"`` | ``"escalation"``
    input_data:
        Raw input fed into this stage (transcript text, sign dict, etc.).
        Must never contain PII.
    output_data:
        Result produced by this stage.  Must never contain PII.
    timestamp:
        UTC timestamp when this log entry was created.
    """

    conversation_id: str = Field(
        ...,
        description="Cross-pipeline correlation key; matches SessionState.",
    )
    stage: str = Field(
        ...,
        description=(
            "One of: 'asr' | 'intake' | 'disambiguation' "
            "| 'risk_combination' | 'escalation'"
        ),
    )
    input_data: Optional[Any] = Field(
        default=None,
        description="Stage input (PII-free).",
    )
    output_data: Optional[Any] = Field(
        default=None,
        description="Stage output (PII-free).",
    )
    timestamp: datetime = Field(
        default_factory=_utcnow,
        description="UTC timestamp of log entry creation.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "conversation_id": "c8e4f3a1-2b7d-4e9a-a012-0f1c3d5e7b89",
                "stage": "intake",
                "input_data": "baby has fast breathing and not feeding well",
                "output_data": {
                    "clear_signs": {"fast_breathing": True, "poor_feeding": True},
                    "vague_signs": [],
                },
            }
        }
    }