/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as AssessmentChatRouteImport } from './routes/assessment.chat'
import { Route as AssessmentProcessingRouteImport } from './routes/assessment.processing'
import { Route as AssessmentResultRouteImport } from './routes/assessment.result'
import { Route as AssessmentVoiceRouteImport } from './routes/assessment.voice'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentChatRoute = AssessmentChatRouteImport.update({
  id: '/assessment/chat',
  path: '/assessment/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentProcessingRoute = AssessmentProcessingRouteImport.update({
  id: '/assessment/processing',
  path: '/assessment/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentResultRoute = AssessmentResultRouteImport.update({
  id: '/assessment/result',
  path: '/assessment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentVoiceRoute = AssessmentVoiceRouteImport.update({
  id: '/assessment/voice',
  path: '/assessment/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/chat': typeof AssessmentChatRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/result': typeof AssessmentResultRoute
  '/assessment/voice': typeof AssessmentVoiceRoute
  '/history/$id': typeof HistoryIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/chat': typeof AssessmentChatRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/result': typeof AssessmentResultRoute
  '/assessment/voice': typeof AssessmentVoiceRoute
  '/history/$id': typeof HistoryIdRoute
  '/assessment': typeof AssessmentIndexRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/chat': typeof AssessmentChatRoute
  '/assessment/processing': typeof AssessmentProcessingRoute
  '/assessment/result': typeof AssessmentResultRoute
  '/assessment/voice': typeof AssessmentVoiceRoute
  '/history/$id': typeof HistoryIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/profile'
    | '/register'
    | '/sitemap.xml'
    | '/assessment/chat'
    | '/assessment/processing'
    | '/assessment/result'
    | '/assessment/voice'
    | '/history/$id'
    | '/assessment/'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/profile'
    | '/register'
    | '/sitemap.xml'
    | '/assessment/chat'
    | '/assessment/processing'
    | '/assessment/result'
    | '/assessment/voice'
    | '/history/$id'
    | '/assessment'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/profile'
    | '/register'
    | '/sitemap.xml'
    | '/assessment/chat'
    | '/assessment/processing'
    | '/assessment/result'
    | '/assessment/voice'
    | '/history/$id'
    | '/assessment/'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssessmentChatRoute: typeof AssessmentChatRoute
  AssessmentProcessingRoute: typeof AssessmentProcessingRoute
  AssessmentResultRoute: typeof AssessmentResultRoute
  AssessmentVoiceRoute: typeof AssessmentVoiceRoute
  HistoryIdRoute: typeof HistoryIdRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/chat': {
      id: '/assessment/chat'
      path: '/assessment/chat'
      fullPath: '/assessment/chat'
      preLoaderRoute: typeof AssessmentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/processing': {
      id: '/assessment/processing'
      path: '/assessment/processing'
      fullPath: '/assessment/processing'
      preLoaderRoute: typeof AssessmentProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/result': {
      id: '/assessment/result'
      path: '/assessment/result'
      fullPath: '/assessment/result'
      preLoaderRoute: typeof AssessmentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/voice': {
      id: '/assessment/voice'
      path: '/assessment/voice'
      fullPath: '/assessment/voice'
      preLoaderRoute: typeof AssessmentVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssessmentChatRoute: AssessmentChatRoute,
  AssessmentProcessingRoute: AssessmentProcessingRoute,
  AssessmentResultRoute: AssessmentResultRoute,
  AssessmentVoiceRoute: AssessmentVoiceRoute,
  HistoryIdRoute: HistoryIdRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
